version: '3.7'

# proxy network, for jenkins-nexus communication channel
networks:
  hostnet:
    external: false
    name: hostnet

services:
  # Jenkins
  jenkins:
    image: jenkins/jenkins
    networks:
      - hostnet
    ports:
      - 8082:8080
    volumes:
      - ./jenkins:/var/jenkins_home
    links:
      - nexus:nexus

  # nexus
  nexus:
    image: sonatype/nexus
    networks:
      - hostnet
    container_name: nexus-container
    ports:
      - 8081:8081
    volumes:
      - ./nexus:/sonatype/nexus /sonatype-work
